cloud:
  aws:
    credentials:
      access-key: AKIA557CH4OHLWLY5ILT
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: ecommerceproductosstorages

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090
